### ISSUE TITLE
Unchanged files after PR merge

### ISSUE THREAD

**Issue by sdbui** [jstty/beelzebub#28]
It seems like the files from PR #17 (bin/index.js & lib/bzCLI.js) remain unchanged in the latest release and all current branches. Perhaps they got reverted back ( I think from c0fdb9da7 ). For example, [what should be merged](https://github.com/jstty/beelzebub/pull/17/files#diff-3cc1ab65bc02a41254283c397ce1d36bR16) vs [what is currently there](https://github.com/jstty/beelzebub/blob/dev/current/lib/bzCLI.js#L17)

**Comment by jstty** [comment]
this is resolved in 3a53aeadd9e9f881b8ab649e6b887b09fd7015c9
